# Data Cleaning

# Import crucial libraries for plotting and exploring data

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
%matplotlib inline

<p>Moreover, the link to the Airline data set already contains a test.csv and train.csv set which is not normally the case. Beacause
a dataset usually comes on its own and it will be split once we get to the Data Analysis stage, where identifying a model for predictions/classfications requires the data to be split into a training and a test set. So to solve this problem we will merge the train and test set together using the pd.concat() </p>

<h3>For good practice, we normally replace whitespace character in columns' names with '_'</h3>

In [3]:
Training_Data = pd.read_csv('train.csv', encoding = 'utf-8')
Training_Data.columns = Training_Data.columns.str.replace(' ', '_')

Testing_Data = pd.read_csv('test.csv', encoding = 'utf-8')
Testing_Data.columns = Testing_Data.columns.str.replace(' ', '_')

Full_Set = pd.concat([Training_Data, Testing_Data]).reset_index(drop=True)

## Execute the code below to create a csv file named output.csv containing all the data.

In [4]:
Full_Set.to_csv('output.csv', index=False)

<h4>We will refer to the the 'Training_Data' and 'Testing_Data' later on when we reach the model identification process.
For now, we'll use 'Full_Set' data for EDA.</h4>

In [5]:
Full_Set
Full_Set.head()

,Unnamed:_0,id,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,...,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes,Arrival_Delay_in_Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [6]:
Full_Set.tail()

,Unnamed:_0,id,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,...,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes,Arrival_Delay_in_Minutes,satisfaction
129875,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,neutral or dissatisfied
129876,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,satisfied
129877,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,neutral or dissatisfied
129878,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,satisfied
129879,25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0.0,neutral or dissatisfied

# Understanding the data

In [7]:
Full_Set.shape

(129880, 25)

In [8]:
Full_Set.columns

Index(['Unnamed:_0', 'id', 'Gender', 'Customer_Type', 'Age', 'Type_of_Travel',
       'Class', 'Flight_Distance', 'Inflight_wifi_service',
       'Departure/Arrival_time_convenient', 'Ease_of_Online_booking',
       'Gate_location', 'Food_and_drink', 'Online_boarding', 'Seat_comfort',
       'Inflight_entertainment', 'On-board_service', 'Leg_room_service',
       'Baggage_handling', 'Checkin_service', 'Inflight_service',
       'Cleanliness', 'Departure_Delay_in_Minutes', 'Arrival_Delay_in_Minutes',
       'satisfaction'],
      dtype='object')

In [9]:
Full_Set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed:_0                         129880 non-null  int64
 1   id                                 129880 non-null  int64
 2   Gender                             129880 non-null  object
 3   Customer_Type                      129880 non-null  object
 4   Age                                129880 non-null  int64
 5   Type_of_Travel                     129880 non-null  object
 6   Class                              129880 non-null  object
 7   Flight_Distance                    129880 non-null  int64
 8   Inflight_wifi_service              129880 non-null  int64
 9   Departure/Arrival_time_convenient  129880 non-null  int64
 10  Ease_of_Online_booking             129880 non-null  int64
 11  Gate_location                      129880 non-null  int64
 12  Food_and_drink                     129880 non-null  int64
 13  Online_boarding                    129880 non-null  int64
 14  Seat_comfort                       129880 non-null  int64
 15  Inflight_entertainment             129880 non-null  int64
 16  On-board_service                   129880 non-null  int64
 17  Leg_room_service                   129880 non-null  int64
 18  Baggage_handling                   129880 non-null  int64
 19  Checkin_service                    129880 non-null  int64
 20  Inflight_service                   129880 non-null  int64
 21  Cleanliness                        129880 non-null  int64
 22  Departure_Delay_in_Minutes         129880 non-null  int64
 23  Arrival_Delay_in_Minutes           129487 non-null  float64
 24  satisfaction                       129880 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 24.8+ MB

### Dropping the first column

In [10]:
Full_Set.drop('Unnamed:_0', axis=1, inplace=True)

In [11]:
Full_Set.columns

Index(['id', 'Gender', 'Customer_Type', 'Age', 'Type_of_Travel', 'Class',
       'Flight_Distance', 'Inflight_wifi_service',
       'Departure/Arrival_time_convenient', 'Ease_of_Online_booking',
       'Gate_location', 'Food_and_drink', 'Online_boarding', 'Seat_comfort',
       'Inflight_entertainment', 'On-board_service', 'Leg_room_service',
       'Baggage_handling', 'Checkin_service', 'Inflight_service',
       'Cleanliness', 'Departure_Delay_in_Minutes', 'Arrival_Delay_in_Minutes',
       'satisfaction'],
      dtype='object')

# Repeat the above processes again to check that we've removed the 'Unnamed:_0' column

In [12]:
Full_Set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 129880 non-null  int64
 1   Gender                             129880 non-null  object
 2   Customer_Type                      129880 non-null  object
 3   Age                                129880 non-null  int64
 4   Type_of_Travel                     129880 non-null  object
 5   Class                              129880 non-null  object
 6   Flight_Distance                    129880 non-null  int64
 7   Inflight_wifi_service              129880 non-null  int64
 8   Departure/Arrival_time_convenient  129880 non-null  int64
 9   Ease_of_Online_booking             129880 non-null  int64
 10  Gate_location                      129880 non-null  int64
 11  Food_and_drink                     129880 non-null  int64
 12  Online_boarding                    129880 non-null  int64
 13  Seat_comfort                       129880 non-null  int64
 14  Inflight_entertainment             129880 non-null  int64
 15  On-board_service                   129880 non-null  int64
 16  Leg_room_service                   129880 non-null  int64
 17  Baggage_handling                   129880 non-null  int64
 18  Checkin_service                    129880 non-null  int64
 19  Inflight_service                   129880 non-null  int64
 20  Cleanliness                        129880 non-null  int64
 21  Departure_Delay_in_Minutes         129880 non-null  int64
 22  Arrival_Delay_in_Minutes           129487 non-null  float64
 23  satisfaction                       129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [13]:
Full_Set.dtypes

id                                     int64
Gender                                object
Customer_Type                         object
Age                                    int64
Type_of_Travel                        object
Class                                 object
Flight_Distance                        int64
Inflight_wifi_service                  int64
Departure/Arrival_time_convenient      int64
Ease_of_Online_booking                 int64
Gate_location                          int64
Food_and_drink                         int64
Online_boarding                        int64
Seat_comfort                           int64
Inflight_entertainment                 int64
On-board_service                       int64
Leg_room_service                       int64
Baggage_handling                       int64
Checkin_service                        int64
Inflight_service                       int64
Cleanliness                            int64
Departure_Delay_in_Minutes             int64
Arrival_Delay_in_Minutes             float64
satisfaction                          object
dtype: object

# Checking for percentages of missing values inside each feature

In [34]:
data_with_nan = [features for features in Full_Set.columns if Full_Set[features].isnull().sum]
for feature in data_with_nan:
    print(feature, np.round(Full_Set[feature].isnull().mean(), 4), '% missing values')

id 0.0 % missing values
Gender 0.0 % missing values
Customer_Type 0.0 % missing values
Age 0.0 % missing values
Type_of_Travel 0.0 % missing values
Class 0.0 % missing values
Flight_Distance 0.0 % missing values
Inflight_wifi_service 0.0 % missing values
Departure/Arrival_time_convenient 0.0 % missing values
Ease_of_Online_booking 0.0 % missing values
Gate_location 0.0 % missing values
Food_and_drink 0.0 % missing values
Online_boarding 0.0 % missing values
Seat_comfort 0.0 % missing values
Inflight_entertainment 0.0 % missing values
On-board_service 0.0 % missing values
Leg_room_service 0.0 % missing values
Baggage_handling 0.0 % missing values
Checkin_service 0.0 % missing values
Inflight_service 0.0 % missing values
Cleanliness 0.0 % missing values
Departure_Delay_in_Minutes 0.0 % missing values
Arrival_Delay_in_Minutes 0.003 % missing values
satisfaction 0.0 % missing values

# Fill missing value with mean value

In [35]:
data = Full_Set.fillna({'Arrival_Delay_in_Minutes' : np.min(Full_Set['Arrival_Delay_in_Minutes'])})
for feature in data_with_nan:
    print(feature, np.round(data[feature].isnull().mean(), 4), '% missing values')

id 0.0 % missing values
Gender 0.0 % missing values
Customer_Type 0.0 % missing values
Age 0.0 % missing values
Type_of_Travel 0.0 % missing values
Class 0.0 % missing values
Flight_Distance 0.0 % missing values
Inflight_wifi_service 0.0 % missing values
Departure/Arrival_time_convenient 0.0 % missing values
Ease_of_Online_booking 0.0 % missing values
Gate_location 0.0 % missing values
Food_and_drink 0.0 % missing values
Online_boarding 0.0 % missing values
Seat_comfort 0.0 % missing values
Inflight_entertainment 0.0 % missing values
On-board_service 0.0 % missing values
Leg_room_service 0.0 % missing values
Baggage_handling 0.0 % missing values
Checkin_service 0.0 % missing values
Inflight_service 0.0 % missing values
Cleanliness 0.0 % missing values
Departure_Delay_in_Minutes 0.0 % missing values
Arrival_Delay_in_Minutes 0.0 % missing values
satisfaction 0.0 % missing values

# Checking for outliers

In [36]:
def detect_outlier(data_set):
    outlier_lst = []
    q1 = data_set.quantile(0.25)
    q3 = data_set.quantile(0.75)
    
    IQR = q3 - q1
    
    lower_bound = q1 - 1.5 * IQR
    upper_bound = q3 + 1.5 * IQR
    
    upper_outliers_index = data_set[data_set > upper_bound].index.tolist()
    lower_outliers_index = data_set[data_set < lower_bound].index.tolist()
    
#     upper_outliers = data_set[data_set > upper_bound].tolist()
#     lower_outliers = data_set[data_set < lower_bound]
    
    print(f'Outliers Index: ', upper_outliers_index)

print(detect_outlier(data['Flight_Distance']))

Outliers Index:  [80, 173, 201, 215, 379, 388, 421, 446, 458, 473, 483, 569, 634, 717, 778, 794, 799, 869, 879, 939, 978, 994, 1061, 1068, 1092, 1101, 1114, 1120, 1186, 1236, 1248, 1252, 1269, 1417, 1425, 1496, 1541, 1548, 1587, 1705, 1752, 1846, 1847, 1876, 1932, 1948, 2156, 2194, 2208, 2213, 2286, 2297, 2363, 2392, 2401, 2495, 2544, 2556, 2619, 2628, 2659, 2736, 2803, 2818, 2847, 2970, 2981, 3027, 3030, 3046, 3090, 3129, 3186, 3282, 3379, 3401, 3405, 3407, 3485, 3486, 3516, 3525, 3660, 3773, 3838, 3866, 3912, 3927, 4003, 4013, 4031, 4071, 4073, 4114, 4134, 4362, 4363, 4539, 4545, 4593, 4676, 4725, 4762, 4794, 4832, 4849, 4930, 4935, 4939, 4941, 5170, 5216, 5276, 5342, 5370, 5381, 5383, 5409, 5466, 5504, 5554, 5583, 5639, 5650, 5703, 5732, 5733, 5743, 5750, 5758, 5779, 5781, 5866, 5903, 5985, 6058, 6135, 6159, 6259, 6328, 6348, 6489, 6506, 6535, 6617, 6753, 6776, 6778, 6812, 6846, 6882, 6959, 6967, 7104, 7106, 7120, 7138, 7150, 7206, 7306, 7326, 7346, 7351, 7355, 7393, 7496, 7648, 7683, 7688, 7690, 7975, 8014, 8039, 8044, 8144, 8217, 8300, 8314, 8334, 8396, 8406, 8414, 8480, 8495, 8520, 8593, 8630, 8672, 8714, 8758, 8822, 8824, 8870, 8913, 8952, 9042, 9069, 9105, 9157, 9170, 9173, 9197, 9257, 9334, 9356, 9452, 9546, 9611, 9627, 9680, 9704, 9852, 9935, 9996, 9999, 10004, 10043, 10130, 10168, 10312, 10400, 10424, 10456, 10481, 10523, 10533, 10563, 10569, 10573, 10654, 10676, 10860, 11055, 11090, 11122, 11132, 11150, 11224, 11257, 11282, 11306, 11336, 11343, 11361, 11374, 11532, 11621, 11649, 11659, 11715, 11723, 11729, 11755, 11788, 11822, 11938, 11982, 12027, 12039, 12219, 12246, 12271, 12275, 12306, 12317, 12405, 12413, 12415, 12418, 12470, 12496, 12519, 12556, 12614, 12669, 12688, 12764, 12769, 12815, 12854, 12924, 12960, 12978, 13063, 13080, 13128, 13144, 13171, 13196, 13260, 13280, 13313, 13347, 13379, 13420, 13462, 13470, 13474, 13548, 13605, 13611, 13612, 13627, 13662, 13670, 13720, 13729, 13789, 13797, 13901, 13959, 13962, 13975, 14129, 14153, 14183, 14187, 14190, 14195, 14260, 14267, 14306, 14334, 14380, 14499, 14782, 14837, 14862, 14913, 14916, 15112, 15136, 15282, 15289, 15351, 15366, 15369, 15494, 15511, 15542, 15545, 15558, 15606, 15625, 15656, 15719, 15744, 15872, 15915, 15941, 16026, 16047, 16113, 16118, 16228, 16318, 16378, 16453, 16496, 16557, 16612, 16614, 16619, 16651, 16676, 16718, 16797, 16830, 16842, 16850, 16866, 16961, 17052, 17062, 17094, 17175, 17194, 17245, 17255, 17269, 17316, 17347, 17373, 17414, 17478, 17491, 17515, 17529, 17582, 17777, 17843, 17872, 17876, 18027, 18044, 18084, 18179, 18188, 18238, 18290, 18307, 18418, 18434, 18466, 18509, 18556, 18616, 18711, 18720, 18730, 18757, 18786, 18909, 18973, 18976, 18977, 19044, 19096, 19143, 19196, 19291, 19298, 19412, 19503, 19583, 19628, 19632, 19633, 19707, 19709, 19741, 19755, 19881, 19951, 20032, 20034, 20099, 20240, 20284, 20298, 20311, 20395, 20410, 20425, 20538, 20560, 20627, 20633, 20791, 20822, 20895, 20922, 20928, 20988, 21126, 21176, 21178, 21191, 21253, 21260, 21338, 21370, 21416, 21428, 21530, 21553, 21670, 21684, 21707, 21734, 21743, 21770, 21780, 21795, 21827, 21927, 21936, 21945, 21969, 21978, 22152, 22174, 22204, 22225, 22251, 22271, 22465, 22522, 22603, 22627, 22644, 22647, 22653, 22691, 22693, 22704, 22791, 22945, 22974, 23017, 23082, 23121, 23126, 23142, 23260, 23349, 23408, 23444, 23521, 23542, 23590, 23602, 23625, 23715, 23756, 23798, 23848, 23849, 23895, 24038, 24091, 24104, 24106, 24148, 24208, 24256, 24291, 24346, 24364, 24395, 24409, 24418, 24457, 24467, 24510, 24520, 24584, 24653, 24676, 24787, 24822, 24847, 24881, 24908, 24928, 24935, 24941, 24995, 24997, 25014, 25020, 25022, 25128, 25186, 25302, 25328, 25508, 25510, 25511, 25545, 25636, 25694, 25707, 25877, 25905, 25954, 25988, 26009, 26032, 26077, 26176, 26249, 26297, 26498, 26538, 26541, 26557, 26594, 26615, 26673, 26814, 26835, 26883, 27094, 27123, 27131, 27140, 27173, 27303, 27329, 27464, 27469, 27487, 27526, 27555, 27611, 27622, 27629, 27659, 27850, 27970, 27973, 27983, 28024, 28050, 28108, 28190, 28388, 28403, 28409, 28437, 28505, 28548, 28692, 28727, 28892, 28913, 28938, 28972, 28988, 29020, 29055, 29077, 29117, 29246, 29461, 29611, 29638, 29653, 29738, 29843, 29875, 29954, 30024, 30049, 30055, 30153, 30201, 30330, 30334, 30429, 30439, 30453, 30553, 30607, 30621, 30673, 30685, 30695, 30739, 30788, 30814, 30825, 30845, 30881, 30903, 30954, 31004, 31083, 31245, 31254, 31369, 31388, 31481, 31626, 31672, 31676, 31748, 31851, 31853, 31858, 31887, 31932, 32013, 32015, 32055, 32061, 32090, 32231, 32360, 32366, 32367, 32378, 32398, 32425, 32451, 32462, 32589, 32598, 32609, 32620, 32669, 32722, 32746, 32775, 32831, 32891, 32929, 33015, 33025, 33094, 33121, 33123, 33151, 33159, 33300, 33316, 33392, 33448, 33497, 33531, 33620, 33766, 33834, 33835, 33900, 33944, 33985, 34002, 34019, 34116, 34151, 34222, 34267, 34284, 34299, 34352, 34444, 34521, 34522, 34640, 34663, 34691, 34698, 34766, 34805, 34907, 35113, 35144, 35281, 35334, 35405, 35416, 35430, 35433, 35446, 35502, 35536, 35551, 35552, 35574, 35777, 35798, 35811, 35835, 35851, 35863, 35871, 35969, 36073, 36114, 36213, 36299, 36469, 36495, 36518, 36558, 36561, 36655, 36669, 36673, 36696, 36706, 36782, 36823, 36922, 37007, 37059, 37083, 37209, 37212, 37315, 37334, 37336, 37482, 37609, 37619, 37652, 37686, 37849, 37850, 37875, 37960, 37965, 38005, 38104, 38146, 38165, 38179, 38284, 38349, 38359, 38379, 38380, 38388, 38396, 38397, 38429, 38510, 38568, 38573, 38580, 38597, 38642, 38677, 38760, 38778, 38829, 38874, 38967, 38976, 39024, 39029, 39036, 39047, 39118, 39128, 39142, 39157, 39225, 39232, 39260, 39263, 39266, 39270, 39295, 39331, 39430, 39629, 39728, 39767, 39800, 39861, 39865, 39888, 39936, 40084, 40151, 40221, 40259, 40264, 40332, 40337, 40423, 40437, 40445, 40477, 40566, 40593, 40625, 40659, 40684, 40721, 40790, 40800, 40904, 40990, 41007, 41012, 41029, 41073, 41102, 41109, 41130, 41285, 41321, 41322, 41388, 41411, 41454, 41486, 41632, 41761, 41819, 41931, 41981, 42006, 42018, 42053, 42081, 42113, 42129, 42157, 42211, 42221, 42269, 42334, 42355, 42364, 42395, 42427, 42496, 42794, 42906, 42914, 42929, 42985, 42989, 43213, 43229, 43294, 43298, 43313, 43348, 43375, 43432, 43466, 43597, 43613, 43682, 43694, 43711, 43775, 43795, 43796, 43801, 43844, 43969, 44038, 44120, 44135, 44140, 44158, 44244, 44286, 44381, 44392, 44429, 44444, 44482, 44597, 44630, 44658, 44740, 44822, 44857, 44933, 44964, 44986, 45004, 45015, 45044, 45064, 45104, 45111, 45205, 45359, 45379, 45380, 45427, 45518, 45530, 45592, 45604, 45606, 45622, 45672, 45690, 45735, 45753, 45775, 45790, 45856, 46042, 46076, 46131, 46174, 46180, 46299, 46325, 46450, 46469, 46507, 46544, 46672, 46704, 46714, 46731, 46791, 46825, 46848, 46938, 46956, 46960, 46993, 47003, 47080, 47089, 47206, 47314, 47497, 47571, 47590, 47651, 47684, 47777, 47812, 47827, 47889, 47956, 48049, 48117, 48137, 48302, 48443, 48562, 48586, 48690, 48694, 48695, 48875, 49106, 49162, 49164, 49208, 49330, 49420, 49426, 49428, 49439, 49446, 49477, 49506, 49546, 49552, 49620, 49638, 49746, 49798, 49835, 49840, 49849, 49889, 49895, 49948, 49970, 50009, 50022, 50028, 50075, 50106, 50169, 50201, 50212, 50300, 50319, 50342, 50432, 50466, 50640, 50715, 50798, 50907, 51002, 51037, 51079, 51091, 51092, 51132, 51240, 51420, 51455, 51457, 51516, 51543, 51569, 51608, 51616, 51624, 51657, 51661, 51718, 51721, 51738, 51791, 51860, 51887, 51942, 51970, 51991, 52041, 52048, 52069, 52154, 52201, 52239, 52261, 52281, 52334, 52354, 52381, 52410, 52493, 52520, 52528, 52668, 52738, 52812, 52820, 52856, 52857, 52923, 53047, 53105, 53163, 53175, 53176, 53178, 53191, 53202, 53310, 53315, 53438, 53498, 53656, 53709, 53714, 53752, 53765, 53768, 53826, 53861, 53882, 53893, 53930, 53957, 53959, 54041, 54042, 54084, 54107, 54122, 54180, 54208, 54222, 54230, 54240, 54284, 54315, 54320, 54364, 54380, 54500, 54514, 54579, 54598, 54684, 54734, 54744, 54787, 54799, 54949, 55021, 55133, 55196, 55304, 55450, 55462, 55527, 55559, 55588, 55612, 55653, 55666, 55732, 55751, 55899, 55935, 55956, 55976, 56038, 56076, 56080, 56106, 56138, 56160, 56297, 56345, 56357, 56394, 56403, 56453, 56467, 56490, 56499, 56517, 56562, 56563, 56592, 56595, 56604, 56614, 56635, 56715, 56723, 56735, 56738, 56741, 56763, 56773, 56867, 56884, 56979, 57053, 57055, 57112, 57171, 57273, 57293, 57326, 57332, 57335, 57408, 57520, 57596, 57605, 57618, 57625, 57670, 57681, 57715, 57786, 57819, 57835, 57847, 57874, 57919, 57960, 58025, 58080, 58096, 58142, 58143, 58206, 58237, 58238, 58304, 58360, 58374, 58399, 58617, 58690, 58704, 58777, 58796, 58877, 58881, 58928, 59005, 59027, 59048, 59087, 59102, 59134, 59196, 59202, 59248, 59262, 59288, 59352, 59359, 59406, 59526, 59532, 59556, 59585, 59593, 59653, 59677, 59710, 59719, 59725, 59740, 59788, 59819, 59831, 59956, 59959, 60040, 60160, 60165, 60267, 60295, 60303, 60317, 60445, 60451, 60471, 60474, 60485, 60497, 60615, 60639, 60668, 60698, 60699, 60726, 60727, 60790, 60814, 60883, 60893, 60928, 60971, 61044, 61074, 61106, 61170, 61222, 61423, 61435, 61442, 61482, 61526, 61595, 61636, 61660, 61692, 61794, 61861, 61887, 61891, 61910, 61915, 61957, 61968, 61996, 62087, 62137, 62192, 62414, 62429, 62556, 62580, 62639, 62689, 62783, 62808, 62937, 62987, 62997, 63096, 63190, 63225, 63342, 63366, 63377, 63463, 63465, 63482, 63522, 63525, 63709, 63728, 63744, 63803, 63811, 63826, 63846, 63966, 64012, 64077, 64087, 64099, 64135, 64153, 64195, 64222, 64245, 64262, 64275, 64306, 64309, 64335, 64345, 64377, 64415, 64438, 64629, 64631, 64660, 64665, 64693, 64722, 64738, 64746, 64768, 64783, 64791, 64798, 64822, 64874, 64976, 64993, 65075, 65094, 65197, 65216, 65217, 65238, 65277, 65346, 65350, 65465, 65475, 65476, 65574, 65646, 65661, 65674, 65720, 65769, 65879, 65923, 65963, 66047, 66262, 66356, 66387, 66454, 66499, 66506, 66543, 66544, 66583, 66597, 66648, 66722, 66758, 66777, 66874, 67065, 67094, 67149, 67156, 67166, 67308, 67309, 67355, 67391, 67472, 67566, 67637, 67767, 67799, 67879, 67883, 67935, 67984, 68048, 68070, 68146, 68219, 68226, 68233, 68395, 68449, 68459, 68547, 68550, 68678, 68716, 68763, 68808, 68842, 68880, 68931, 68978, 69087, 69131, 69207, 69209, 69220, 69226, 69256, 69273, 69348, 69357, 69383, 69463, 69582, 69588, 69604, 69610, 69664, 69682, 69685, 69741, 69802, 69853, 69872, 69893, 69937, 69947, 70019, 70038, 70201, 70392, 70549, 70583, 70628, 70674, 70740, 70782, 70818, 70835, 70903, 71041, 71162, 71164, 71199, 71222, 71314, 71398, 71447, 71465, 71500, 71510, 71544, 71571, 71601, 71749, 71750, 71752, 71786, 71802, 71828, 71925, 71967, 72203, 72277, 72278, 72326, 72427, 72436, 72497, 72526, 72533, 72565, 72572, 72621, 72645, 72683, 72787, 72868, 72908, 72926, 72940, 72943, 72957, 72976, 72996, 72999, 73008, 73025, 73032, 73073, 73114, 73145, 73174, 73191, 73212, 73216, 73307, 73335, 73436, 73476, 73529, 73551, 73563, 73622, 73677, 73707, 73779, 73819, 73823, 73886, 73905, 73922, 73950, 74014, 74023, 74045, 74105, 74118, 74135, 74143, 74271, 74298, 74365, 74394, 74537, 74541, 74584, 74713, 74714, 74729, 74836, 74837, 74876, 74982, 74989, 75027, 75095, 75255, 75295, 75309, 75357, 75373, 75385, 75387, 75399, 75403, 75419, 75500, 75559, 75594, 75613, 75636, 75668, 75721, 75808, 75853, 75897, 75975, 76000, 76061, 76149, 76181, 76184, 76192, 76274, 76288, 76335, 76340, 76343, 76360, 76377, 76419, 76449, 76471, 76488, 76522, 76528, 76565, 76662, 76673, 76706, 76754, 76763, 76791, 76942, 76946, 76980, 77035, 77046, 77169, 77247, 77276, 77316, 77379, 77415, 77431, 77451, 77615, 77643, 77782, 77861, 77894, 77937, 77959, 77981, 77993, 77996, 78048, 78072, 78149, 78234, 78263, 78331, 78361, 78411, 78416, 78441, 78475, 78480, 78486, 78565, 78618, 78643, 78677, 78714, 78755, 78886, 78932, 78947, 78952, 78975, 78977, 79063, 79078, 79079, 79212, 79239, 79278, 79323, 79345, 79357, 79358, 79377, 79390, 79442, 79488, 79539, 79574, 79581, 79718, 79770, 79812, 79871, 79877, 79888, 79965, 80029, 80121, 80203, 80375, 80411, 80450, 80476, 80557, 80578, 80591, 80617, 80661, 80710, 80719, 80746, 80765, 80856, 80876, 80934, 80978, 80984, 81193, 81203, 81230, 81241, 81285, 81290, 81503, 81567, 81600, 81624, 81664, 81746, 81831, 81871, 81955, 81974, 82021, 82166, 82264, 82279, 82309, 82435, 82493, 82533, 82585, 82596, 82616, 82682, 82684, 82699, 82759, 82783, 82876, 82889, 82904, 82965, 83080, 83134, 83293, 83351, 83356, 83502, 83570, 83571, 83662, 83717, 83999, 84001, 84106, 84199, 84221, 84229, 84246, 84274, 84331, 84443, 84469, 84498, 84550, 84724, 84732, 84867, 84951, 84979, 84996, 85014, 85049, 85121, 85127, 85130, 85132, 85138, 85142, 85249, 85263, 85329, 85333, 85345, 85347, 85488, 85582, 85598, 85626, 85652, 85697, 85706, 85730, 85794, 85889, 85893, 85896, 85920, 85945, 85966, 86020, 86038, 86146, 86172, 86206, 86209, 86218, 86227, 86335, 86414, 86428, 86465, 86474, 86477, 86605, 86671, 86722, 86785, 86800, 86859, 86973, 87008, 87047, 87092, 87108, 87127, 87229, 87379, 87391, 87416, 87464, 87533, 87558, 87732, 87804, 87859, 87915, 87936, 88032, 88054, 88092, 88128, 88151, 88187, 88255, 88366, 88425, 88434, 88450, 88475, 88555, 88672, 88738, 88742, 88746, 88782, 88847, 88868, 88869, 88939, 89000, 89015, 89022, 89037, 89042, 89176, 89312, 89337, 89419, 89435, 89460, 89522, 89538, 89548, 89563, 89589, 89611, 89623, 89637, 89661, 89673, 89689, 89755, 89769, 89770, 89787, 89825, 89884, 89901, 89912, 89922, 89933, 89948, 89953, 89988, 90018, 90019, 90081, 90118, 90125, 90198, 90265, 90353, 90385, 90419, 90457, 90494, 90513, 90565, 90658, 90769, 90774, 90836, 90915, 90951, 90959, 90964, 91030, 91093, 91103, 91143, 91147, 91185, 91198, 91207, 91253, 91311, 91337, 91374, 91375, 91410, 91430, 91464, 91542, 91570, 91677, 91698, 91794, 91805, 91923, 91932, 91940, 91959, 91996, 92021, 92175, 92300, 92344, 92361, 92376, 92430, 92502, 92554, 92567, 92661, 92740, 92759, 92765, 92775, 92804, 92825, 92848, 92874, 92890, 92900, 92914, 92974, 93051, 93058, 93076, 93108, 93139, 93170, 93229, 93273, 93308, 93434, 93447, 93472, 93512, 93520, 93571, 93642, 93755, 93802, 93929, 93941, 94007, 94093, 94156, 94180, 94209, 94241, 94301, 94306, 94326, 94342, 94363, 94386, 94476, 94552, 94664, 94668, 94712, 94760, 94978, 94979, 94987, 95018, 95166, 95194, 95264, 95290, 95306, 95344, 95345, 95401, 95552, 95698, 95717, 95747, 95749, 95885, 95895, 95982, 95998, 96012, 96043, 96054, 96078, 96113, 96193, 96234, 96276, 96326, 96340, 96386, 96417, 96430, 96436, 96499, 96527, 96535, 96572, 96592, 96646, 96777, 96790, 96804, 96842, 96860, 96918, 96920, 96960, 97012, 97151, 97179, 97197, 97222, 97224, 97234, 97261, 97370, 97396, 97400, 97401, 97419, 97429, 97455, 97470, 97502, 97532, 97561, 97569, 97595, 97695, 97758, 97784, 97862, 97909, 97913, 97969, 97970, 98000, 98035, 98097, 98118, 98205, 98275, 98323, 98331, 98385, 98408, 98410, 98413, 98435, 98436, 98484, 98540, 98603, 98625, 98634, 98668, 98713, 98754, 98783, 98846, 98859, 98881, 98944, 99005, 99070, 99184, 99205, 99270, 99285, 99304, 99306, 99362, 99404, 99453, 99465, 99482, 99498, 99522, 99524, 99527, 99614, 99618, 99690, 99703, 99720, 99723, 99763, 99813, 99869, 99898, 100032, 100126, 100133, 100151, 100207, 100235, 100266, 100302, 100350, 100387, 100433, 100478, 100558, 100605, 100680, 100704, 100722, 100730, 100744, 100784, 100883, 100928, 100950, 100959, 101177, 101236, 101243, 101358, 101402, 101424, 101448, 101473, 101488, 101501, 101504, 101544, 101612, 101623, 101664, 101683, 101698, 101831, 101861, 101871, 101883, 101942, 101969, 101996, 101998, 102044, 102135, 102208, 102223, 102267, 102337, 102344, 102356, 102455, 102474, 102506, 102531, 102555, 102571, 102619, 102753, 102861, 102870, 102905, 102913, 103063, 103101, 103103, 103161, 103241, 103322, 103344, 103357, 103448, 103512, 103534, 103553, 103565, 103648, 103727, 103865, 103889, 103910, 103923, 104049, 104074, 104084, 104177, 104178, 104209, 104279, 104338, 104341, 104356, 104399, 104514, 104519, 104657, 104661, 104672, 104694, 104698, 104706, 104757, 104840, 104850, 104907, 104966, 105029, 105075, 105149, 105183, 105189, 105259, 105262, 105294, 105339, 105394, 105431, 105442, 105494, 105502, 105792, 105802, 105841, 105865, 105884, 105921, 106048, 106091, 106167, 106173, 106188, 106217, 106246, 106331, 106336, 106436, 106474, 106525, 106572, 106584, 106587, 106603, 106728, 106862, 106931, 106947, 107038, 107042, 107056, 107098, 107140, 107386, 107389, 107406, 107457, 107521, 107549, 107566, 107577, 107609, 107699, 107857, 107877, 107905, 107911, 107915, 107948, 107958, 108034, 108124, 108224, 108270, 108315, 108356, 108358, 108402, 108421, 108466, 108470, 108523, 108547, 108571, 108614, 108691, 108801, 109004, 109065, 109110, 109167, 109194, 109234, 109255, 109262, 109272, 109288, 109308, 109363, 109380, 109414, 109489, 109503, 109512, 109581, 109630, 109724, 109728, 109733, 109795, 109796, 109797, 109800, 109935, 109977, 110002, 110003, 110011, 110038, 110070, 110102, 110113, 110227, 110252, 110262, 110325, 110380, 110575, 110640, 110680, 110697, 110799, 110853, 110886, 110902, 110915, 110927, 110955, 110971, 110982, 111030, 111049, 111115, 111195, 111238, 111240, 111434, 111447, 111464, 111635, 111644, 111689, 111755, 111772, 111777, 111824, 111863, 111927, 111953, 111968, 111971, 111973, 112096, 112114, 112138, 112196, 112253, 112264, 112280, 112323, 112347, 112353, 112372, 112544, 112548, 112556, 112595, 112700, 112723, 112777, 112795, 112861, 112979, 113035, 113039, 113062, 113069, 113165, 113178, 113180, 113210, 113280, 113345, 113350, 113454, 113505, 113643, 113710, 113757, 113779, 113828, 113950, 113994, 114030, 114146, 114147, 114161, 114174, 114179, 114558, 114610, 114636, 114737, 114751, 114813, 114816, 114826, 114850, 114901, 114940, 114941, 114949, 114993, 115027, 115065, 115091, 115179, 115322, 115328, 115361, 115407, 115432, 115499, 115503, 115507, 115519, 115548, 115556, 115584, 115627, 115671, 115683, 115725, 115804, 115812, 115816, 115856, 115924, 115946, 115969, 115971, 116007, 116132, 116229, 116242, 116303, 116436, 116453, 116662, 116695, 116756, 116850, 116912, 116920, 116964, 116986, 117029, 117036, 117059, 117079, 117099, 117224, 117233, 117254, 117263, 117274, 117286, 117308, 117313, 117368, 117423, 117442, 117501, 117570, 117588, 117599, 117620, 117628, 117695, 117711, 117736, 117754, 117758, 117786, 117862, 117871, 118090, 118108, 118140, 118165, 118222, 118223, 118260, 118272, 118323, 118413, 118462, 118463, 118495, 118496, 118515, 118519, 118536, 118597, 118632, 118682, 118769, 118770, 118810, 118924, 118993, 119033, 119064, 119147, 119154, 119157, 119176, 119180, 119244, 119264, 119358, 119390, 119405, 119443, 119541, 119547, 119608, 119612, 119647, 119765, 119772, 119844, 119854, 119904, 120015, 120161, 120311, 120333, 120452, 120460, 120568, 120576, 120587, 120590, 120634, 120655, 120699, 120735, 120825, 120878, 120907, 120931, 120941, 120965, 120967, 120972, 120974, 121078, 121080, 121155, 121157, 121196, 121244, 121253, 121254, 121296, 121359, 121362, 121401, 121475, 121487, 121519, 121544, 121551, 121802, 121866, 121872, 121894, 121914, 121977, 121991, 122057, 122072, 122099, 122133, 122142, 122150, 122182, 122189, 122195, 122215, 122249, 122265, 122287, 122463, 122493, 122507, 122546, 122599, 122653, 122701, 122765, 122788, 122800, 122900, 122901, 122943, 122993, 123045, 123108, 123155, 123166, 123198, 123213, 123230, 123318, 123338, 123415, 123438, 123463, 123466, 123503, 123579, 123602, 123615, 123616, 123641, 123738, 123789, 123791, 123802, 123852, 123911, 124117, 124251, 124317, 124454, 124466, 124504, 124531, 124582, 124590, 124634, 124677, 124772, 124864, 124902, 124906, 124930, 124939, 124941, 124995, 125009, 125011, 125039, 125174, 125264, 125292, 125321, 125336, 125374, 125389, 125454, 125459, 125577, 125583, 125630, 125639, 125657, 125665, 125680, 125714, 125785, 125880, 125928, 126012, 126032, 126053, 126092, 126155, 126204, 126206, 126219, 126327, 126387, 126411, 126506, 126514, 126524, 126531, 126589, 126594, 126639, 126686, 126704, 126721, 126841, 126915, 126976, 126979, 126986, 12701

In [8]:
data.head()

,Unnamed:_0,id,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,...,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes,Arrival_Delay_in_Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [37]:
data.to_csv('eda_done.csv',index=True)